<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Calendrier extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Intervention_model');

    } 

    /*
     * Listing of company
     */
    function index()
    {
        $data['_view'] = 'calendrier/index';
        $this->load->view('layouts/main',$data);
    }
    function calendar_json(){
        $data['intervention'] =json_encode( $this->Intervention_model->get_json_intervention());
        echo        $data['intervention'];
    }

}
