<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Company_model');
    } 

    /*
     * Listing of company
     */
    function index()
    {
        $data['company'] = $this->Company_model->get_all_company();
        
        $data['_view'] = 'company/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new company
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','max_length[50]');
		$this->form_validation->set_rules('tel','Tel','max_length[20]');
		$this->form_validation->set_rules('fax','Fax','max_length[20]');
		$this->form_validation->set_rules('ville','Ville','max_length[20]');
		$this->form_validation->set_rules('email','Email','max_length[50]|valid_email');
		$this->form_validation->set_rules('adresse','Adresse','max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'tel' => $this->input->post('tel'),
				'fax' => $this->input->post('fax'),
				'ville' => $this->input->post('ville'),
				'email' => $this->input->post('email'),
				'adresse' => $this->input->post('adresse'),
            );
            
            $company_id = $this->Company_model->add_company($params);
            redirect('company/index');
        }
        else
        {            
            $data['_view'] = 'company/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a company
     */
    function edit($id)
    {   
        // check if the company exists before trying to edit it
        $data['company'] = $this->Company_model->get_company($id);
        
        if(isset($data['company']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','max_length[50]');
			$this->form_validation->set_rules('tel','Tel','max_length[20]');
			$this->form_validation->set_rules('fax','Fax','max_length[20]');
			$this->form_validation->set_rules('ville','Ville','max_length[20]');
			$this->form_validation->set_rules('email','Email','max_length[50]|valid_email');
			$this->form_validation->set_rules('adresse','Adresse','max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'tel' => $this->input->post('tel'),
					'fax' => $this->input->post('fax'),
					'ville' => $this->input->post('ville'),
					'email' => $this->input->post('email'),
					'adresse' => $this->input->post('adresse'),
                );

                $this->Company_model->update_company($id,$params);            
                redirect('company/index');
            }
            else
            {
                $data['_view'] = 'company/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The company you are trying to edit does not exist.');
    } 

    /*
     * Deleting company
     */
    function remove($id)
    {
        $company = $this->Company_model->get_company($id);

        // check if the company exists before trying to delete it
        if(isset($company['id']))
        {
            $this->Company_model->delete_company($id);
            redirect('company/index');
        }
        else
            show_error('The company you are trying to delete does not exist.');
    }
    
}
