<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contrat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contrat_model');
    } 

    /*
     * Listing of contrat
     */
    function index()
    {
        $data['contrat'] = $this->Contrat_model->get_all_contrat();
        
        $data['_view'] = 'contrat/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contrat
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('type','Type','max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'date_deb' => $this->input->post('date_deb'),
				'date_fin' => $this->input->post('date_fin'),
				'type' => $this->input->post('type'),
            );
            
            $contrat_id = $this->Contrat_model->add_contrat($params);
            redirect('contrat/index');
        }
        else
        {            
            $data['_view'] = 'contrat/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contrat
     */
    function edit($id)
    {   
        // check if the contrat exists before trying to edit it
        $data['contrat'] = $this->Contrat_model->get_contrat($id);
        
        if(isset($data['contrat']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('type','Type','max_length[20]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'date_deb' => $this->input->post('date_deb'),
					'date_fin' => $this->input->post('date_fin'),
					'type' => $this->input->post('type'),
                );

                $this->Contrat_model->update_contrat($id,$params);            
                redirect('contrat/index');
            }
            else
            {
                $data['_view'] = 'contrat/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contrat you are trying to edit does not exist.');
    } 

    /*
     * Deleting contrat
     */
    function remove($id)
    {
        $contrat = $this->Contrat_model->get_contrat($id);

        // check if the contrat exists before trying to delete it
        if(isset($contrat['id']))
        {
            $this->Contrat_model->delete_contrat($id);
            redirect('contrat/index');
        }
        else
            show_error('The contrat you are trying to delete does not exist.');
    }
    
}
