<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        // die(var_dump($this->session->userdata('logged_in') ["role"]));
        
    }

    function index()
    {
        
        $this->load->model('Reclamation_model');        
        $data['reclamations'] = $this->Reclamation_model->reclamation_sociter();
        $this->load->model('User_model');        
        $data['users'] = $this->User_model->user_number();
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
    
    function notif()
    {

            $this->load->model('Reclamation_model');
            $data = $this->Reclamation_model->get_info_ajax();
        echo json_encode($data);
    }
    function generate_pdf($id){
        $this->load->model('Contrat_model');
        $data = $this->Contrat_model->get_contrat_societer($id);
        $this->load->library('Pdf');
        $pdf = new Pdf('P', 'mm', 'A4', true, 'UTF-8', false);
        $pdf->SetTitle('My Title');
        $pdf->AddPage();
        $html='
        <h1>Contrat pdf</h1>
        <table style="width:100%" border="1">
        <tr>
          <th>type</th>
          <th>date de début</th> 
          <th>date de fin</th>
          <th>societer</th>
        </tr>
        <tr>
        <td>'.$data['type'].'</td>
          <td>'.$data['date_deb'].'</td>
          <td>'.$data['date_fin'].'</td>
          <td>'.$data['name'].'</td>
        </tr>

      </table>
      ';
        $pdf->writeHTML($html);
        $pdf->Output('name.pdf', 'D');

    }

}
