<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Intervention_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get intervention by id
     */
    function get_intervention($id)
    {
        return $this->db->get_where('intervention',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all intervention
     */
    function get_all_intervention()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('intervention')->result_array();
    }
            /*
     * Get all intervention
     */
    function get_json_intervention()
    {
        $this->db->select('description as title , date_heure as start');
        $this->db->where('active', 1);        
        return $this->db->get('intervention')->result_array();
    }
    function get_json_intervont()
    {
        $this->db->select('description as title , date_heure as start');
        $this->db->where('id_invention',$this->session->userdata('logged_in')['users_id']);        
        $this->db->where('active', 1);        
        return $this->db->get('intervention')->result_array();
    }
        
        
    /*
     * Get all intervention
     */
    function get_client_intervention()
    {
        $this->db->where('id_invention',  $this->session->userdata('logged_in')['users_id']);
        $this->db->order_by('active', 'asc');
        return $this->db->get('intervention')->result_array();
    }
        
    /*
     * function to add new intervention
     */
    function add_intervention($params)
    {
        $this->db->insert('intervention',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update intervention
     */
    function update_intervention($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('intervention',$params);
    }
    
    function update_active($id)
    {
        $this->db->where('id',$id);
        $this->db->set('active',1);
        return $this->db->update('intervention');
    }
    function update_non_active($id)
    {
        $this->db->where('id',$id);
        $this->db->set('active',0);
        return $this->db->update('intervention');
    }
    
    /*
     * function to delete intervention
     */
    function delete_intervention($id)
    {
        return $this->db->delete('intervention',array('id'=>$id));
    }
}
